name: Distribute metadata changes

on:
  push:
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      gamma-insar: ${{ steps.filter.outputs.gamma-insar }}
      gamma-rtc: ${{ steps.filter.outputs.gamma-rtc }}
      isce-insar: ${{ steps.filter.outputs.isce-insar }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: dorny/paths-filter@v2.2.0
        id: filter
        with:
          # inline YAML
          filters: |
            gamma-insar:
              - 'GAMMA/InSAR/*'
            gamma-rtc:
              - 'GAMMA/RTC/*'
            isce-insar:
              - 'ISCE/InSAR/*'

      - name: GAMMA InSAR patch
        if: steps.filter.outputs.gamma-insar == 'true'
        run: |
          git diff ${{ github.event.before }} $GITHUB_SHA -- GAMMA/InSAR/* > hyp3-insar-gamma-${GITHUB_SHA:0:7}.patch

      - name: GAMMA RTC patch
        if: steps.filter.outputs.gamma-rtc == 'true'
        run: |
          git diff ${{ github.event.before }} $GITHUB_SHA -- GAMMA/RTC/* > hyp3-rtc-gamma-${GITHUB_SHA:0:7}.patch

      - name: ISCE InSAR patch
        if: steps.filter.outputs.isce-insar == 'true'
        run: |
          git diff ${{ github.event.before }} $GITHUB_SHA -- ISCE/InSAR/* > hyp3-insar-isce-${GITHUB_SHA:0:7}.patch

      - name: upload patch
        uses: actions/upload-artifact@v2
        # NOTE: Will warn, not error, if no matches found
        with:
          name: patches
          path: 'hyp3-*.patch'


  hyp3-insar-gamma:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.gamma-insar == 'true' }}
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ASFHyP3/hyp3-insar-gamma
          token: ${{ secrets.TOOLS_BOT_PAK }}
      - uses: actions/download-artifact@v2
        with:
          name: patches

      - name: create patch branch and open PR
        id: patch
        run: |
          git config user.email "UAF-asf-apd@alaska.edu"
          git config user.name "tools-bot"

          export PATCH_FILE=$(find . -iname "hyp3-insar-gamma-*.patch" | head -1)
          export PATCH_BRANCH=${PATCH_FILE#./}
          export PATCH_BRANCH=${PATCH_BRANCH%.patch}
          echo "::set-output name=branch::${PATCH_BRANCH}"
          git checkout -b $PATCH_BRANCH
          cd hyp3_insar_gamma/etc
          patch -p3 < ../../${PATCH_FILE}
          git add .
          git commit -m "Apply ${PATCH_FILE}"
          git push origin $PATCH_BRANCH

          echo -e "Update metadata templates\n" > pr-message.md
          echo -e "Applying $PATCH_FILE, see:" >> pr-message.md
          echo -e "https://github.com/ASFHyP3/hyp3-metadata-templates/compare/${{ github.event.before }}..$GITHUB_SHA" >> pr-message.md

          hub pull-request -f -r ASFHyP3/tools -l tools-bot,documentation -F pr-message.md


  hyp3-rtc-gamma:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.gamma-rtc == 'true' }}
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ASFHyP3/hyp3-rtc-gamma
          token: ${{ secrets.TOOLS_BOT_PAK }}
      - uses: actions/download-artifact@v2
        with:
          name: patches

      - name: create patch branch and open PR
        id: patch
        run: |
          git config user.email "UAF-asf-apd@alaska.edu"
          git config user.name "tools-bot"

          export PATCH_FILE=$(find . -iname "hyp3-rtc-gamma-*.patch" | head -1)
          export PATCH_BRANCH=${PATCH_FILE#./}
          export PATCH_BRANCH=${PATCH_BRANCH%.patch}
          echo "::set-output name=branch::${PATCH_BRANCH}"
          git checkout -b $PATCH_BRANCH
          cd hyp3_rtc_gamma/etc
          patch -p3 < ../../${PATCH_FILE}
          git add .
          git commit -m "Apply ${PATCH_FILE}"
          git push origin $PATCH_BRANCH

          echo -e "Update metadata templates\n" > pr-message.md
          echo -e "Applying $PATCH_FILE, see:" >> pr-message.md
          echo -e "https://github.com/ASFHyP3/hyp3-metadata-templates/compare/${{ github.event.before }}..$GITHUB_SHA" >> pr-message.md

          hub pull-request -f -r ASFHyP3/tools -l tools-bot,documentation -F pr-message.md


  hyp3-insar-isce:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.isce-insar == 'true' }}
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ASFHyP3/hyp3-insar-isce
          token: ${{ secrets.TOOLS_BOT_PAK }}
      - uses: actions/download-artifact@v2
        with:
          name: patches

      - name: create patch branch and open PR
        id: patch
        run: |
          git config user.email "UAF-asf-apd@alaska.edu"
          git config user.name "tools-bot"

          export PATCH_FILE=$(find . -iname "hyp3-insar-isce-*.patch" | head -1)
          export PATCH_BRANCH=${PATCH_FILE#./}
          export PATCH_BRANCH=${PATCH_BRANCH%.patch}
          echo "::set-output name=branch::${PATCH_BRANCH}"
          git checkout -b $PATCH_BRANCH
          cd hyp3_insar_isce/etc
          patch -p3 < ../../${PATCH_FILE}
          git add .
          git commit -m "Apply ${PATCH_FILE}"
          git push origin $PATCH_BRANCH

          echo -e "Update metadata templates\n" > pr-message.md
          echo -e "Applying $PATCH_FILE, see:" >> pr-message.md
          echo -e "https://github.com/ASFHyP3/hyp3-metadata-templates/compare/${{ github.event.before }}..$GITHUB_SHA" >> pr-message.md

          hub pull-request -f -r ASFHyP3/tools -l tools-bot,documentation -F pr-message.md
